[project]
name = "traveller-book-parser"
requires-python = ">=3.11"

[tool.ruff]
select = [
    "F",
    "E",
    "W",
    "I",
    "N",
    "D",
    "ANN",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "ISC",
    "G",
    "INP",
    "SIM",
    "TID",
    "TCH",
    "ARG",
    "PTH",
    "PERF",
    "RUF",
    "UP",
]
ignore = [
    "ANN101", # https://beta.ruff.rs/docs/rules/missing-type-self/
    "A003", # (class attribute) https://beta.ruff.rs/docs/rules/builtin-attribute-shadowing/
    "S101",  # Use of assert detected
    "D1",  # Missing docstrings
    "D203",  # https://beta.ruff.rs/docs/rules/one-blank-line-before-class/
    "D213",  # https://beta.ruff.rs/docs/rules/multi-line-summary-second-line/
    "E501",  # https://beta.ruff.rs/docs/rules/line-too-long/
]

#fix = true

[tool.ruff.flake8-annotations]
suppress-none-returning = true


[tool.ruff.isort]
force-sort-within-sections = true
split-on-trailing-comma = false

[tool.yapf]
dedent_closing_brackets = true
space_between_ending_comma_and_closing_bracket = false
